name: Azure Bicep Deployment

on:
  push:
    branches:
      - main  # Trigger the deployment when changes are pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This step checks out the code in the repository

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1  # This step installs the Azure CLI

    - name: Login to Azure
      uses: azure/login@v1  # This step authenticates with Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure credentials stored in GitHub secrets

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --resource-group BCSAI2024-DEVOPS-STUDENTS-A-DEV \  
          --template-file main.bicep \
          --parameters parameters.bicep  # Parameters file for values like resource names and locations
