name: Azure Bicep Deployment

on:
  push:
    branches:
      - main  # Trigger the deployment when changes are pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner

    steps:
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build

    steps:

      # Checkout code
    - uses: actions/checkout@main

    - name: Download Bicep build artifact
      uses: actions/download-artifact@v4
      with:
          name: bicep-build


    - name: Login to Azure
      uses: azure/login@v1  # This step authenticates with Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure credentials stored in GitHub secrets

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --resource-group BCSAI2024-DEVOPS-STUDENTS-A-DEV \  
          --template-file main.bicep \
          --parameters parameters.bicep  # Parameters file for values like resource names and locations
